config/routes.rb
VhstubeApp::Application.routes.draw do
  resources :videos
  get '/home' => 'videos#home', :as => 'video_home'
  get '/video/delete/:id' => 'videos#delete', :as => 'video_delete'
  post '/video/update/:id' => 'videos#update', :as => 'video_update'
  root to: "videos#home"

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :description, :genre, :title, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def home

  end

  def index
    @genre_list = Video.all.map {|v| v.genre}.uniq
    if params[:filter] 
      @users_videos = Video.where(genre: params[:filter])
    else
      @users_videos = Video.order(:title)
    end
  end
  
  def new


  end

  def create
    Video.create(params["video"])

    redirect_to videos_path

  end

  def show

    @url = Video.find(params[:id]).url

  end

  def delete
    Video.find(params[:id]).destroy
    redirect_to videos_path
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    Video.find_by_id(params["id"]).update_attributes(params["video"])
    redirect_to videos_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VhstubeApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Inconsolata' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Gochi+Hand' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=VT323' rel='stylesheet' type='text/css'>
</head>
<body>
<main>
<%= yield %>
</main>
</body>
</html>

app/views/videos/edit.html.erb
<h2>Edit a clip from your library</h2>
<div class="new_video" >
  <img src="/vhs_tape.png" />
  <form action='<%= video_update_path %>' method='post'>
    <table>
      <tr>
        <td>Title</td>
        <td><input type='text' name='video[title]' value="<%= @video.title %>" autofocus></td>
      </tr>
      <tr>
        <td>Description</td>
        <td><textarea rows=3  cols=20  name='video[description]' ><%= @video.description %></textarea></td>
      </tr>
      <tr>
        <td>You tube id</td>
        <td><input type='text' name='video[url]' value="<%= @video.url %>"></td>
      </tr>
      <tr>
        <td>Genre</td>
        <td><input type='text' name='video[genre]' value="<%= @video.genre %>"></td>
      </tr>
      <tr>
        <td></td>
        <td><button>S U B M I T</button></td>
      </tr>
    </table>
  </form>
</div>

app/views/videos/home.html.erb
<img class="logo" src="/vhs_tube_logo.png" />


<nav class="main">
  <a href="<%= videos_path %>"><img class="play_nav" src="/play_button_front.png" /></a>
  <a href="<%= new_video_path %>"><img class="rec_nav" src="/record_button.png" /></a>
</nav>

app/views/videos/index.html.erb
<section class="show">

<a href="<%= new_video_path %>"><p class="menu">Add a clip</p><img class="show_play" src="/record_button.png" /></a>
<a href="/"><img class="show_logo" src="vhs_tube_logo.png" /></a>
<div class="genre_menu">
  
  <div class="menu">Filter By Genre</div>
  <ul>
    <li><a href="<%= videos_path %>">All</a></li>
    <% @genre_list.each do |genre| %>
      <li><a href="?filter=<%= genre %>"><%= genre %></a></li>
    <% end %>
  </ul>
  <img class="show_filter" src="/filter.png" />
</div>




    <div class="tv">
      <img src="old_tv_cropped.png" />
    </div>

</section>




<section class="library">

   
    <% @users_videos.each do |video| %>
         <div class="video">
            <img class="video_spine" src='vhs_spine.jpg' />
            <h3 class="video_title"> <%= video.title %> : <%= video.genre %></h3>
            <p class="description">  Title: <%= video.title %> <br />Description: <%= video.description %> <br /> Genre: <%= video.genre %> </p>    
             <img class="youtube" src="http://img.youtube.com/vi/<%= video["url"] %>/2.jpg" /> 
            <a class="delete" href="<%= video_delete_path(video) %>"a>Delete</a>
            <a class= "edit" href="<%= edit_video_path(video) %>"a>Edit</a>
            <a href="<%= video_path(video) %>"><img class="play_button" src='play_button.png' /></a>
         </div>
    <% end %>
    
</section>

app/views/videos/new.html.erb
<h2>Add a clip to your library</h2>
<div class="new_video" >
  <img src="/vhs_tape.png" />
  <form action='<%= videos_path %>' method='post'>
    <table>
      <tr>
        <td>Title</td>
        <td><input type='text' name='video[title]' autofocus></td>
      </tr>
      <tr>
        <td>Description</td>
        <td><textarea rows=3  cols=20  name='video[description]' ></textarea></td>
      </tr>
      <tr>
        <td>You tube id</td>
        <td><input type='text' name='video[url]'></td>
      </tr>
      <tr>
        <td>Genre</td>
        <td><input type='text' name='video[genre]'></td>
      </tr>
      <tr>
        <td></td>
        <td><button>S U B M I T</button></td>
      </tr>
    </table>
  </form>
</div>

app/views/videos/show.html.erb
<section class="play">
  <nav>
    <a href="<%= videos_path %>"><p class="menu">List CLips</p><img class="play_play" src="/play_button_front.png" /></a>
    <a href="/"><img class="play_logo" src="/vhs_tube_logo.png" /></a>
    <a href="<%= new_video_path %>"><img class="play_play2" src="/record_button.png" /><p class="menu2">Add a clip</p></a>
  </nav>
    <div class="tv_play">
      <img src="/old_tv_cropped.png" />
       <iframe width="560" height="315"  src="//www.youtube.com/embed/<%= @url %>" frameborder="0" allowfullscreen></iframe>
      <ifram 
    </div>

</section>